### ISSUE TITLE
How do I get a list of interviewers 

### ISSUE THREAD

**Issue by BECollymore** [SlyNet/SurveySolutionsClient#11]
Hi,
I am looking at the test code and the following is possible:
var supervisor = await this.service.Users.GetUserDetailsAsync("sup");
and this gives a list of supervisors for a given workspace.
How can that functionality be replicated for interviewers, currently a guid Id value is required, but I am not sure where this Id can be retrieved or if this is the best approach to solve my problem of getting a list of interviewers. Please help me. Thanks.

**Comment by SlyNet** [comment]
Please review [this](https://github.com/SlyNet/SurveySolutionsClient/blob/main/src/SurveySolutionsClient.Tests/GrapqlTests.cs#L126) example
