### ISSUE TITLE
Missing "interviewsNeeded" in GraphQl AssignmentsFilter 

### ISSUE THREAD

**Issue by Bacis55** [SlyNet/SurveySolutionsClient#12]
Hi,
I`m trying to filter assingments what are not completed yet. I found that there are missing option for filtering interviewsNeeded in SurveySolutionsClient.GraphQl AssignmentsFilter. Also is missing filtering by email, CalendarEvent and CreatedAtUtc. I think so it could be useful in some needs to filter by CalendarEvent and CreatedAtUtc. Is it possible to fix it?

Thank you
MB

![image](https://user-images.githubusercontent.com/65445700/161923416-038b091a-8e25-4c57-bdac-ff56bc497733.png)
![image](https://user-images.githubusercontent.com/65445700/161923658-89980106-67f6-4eec-820a-1cc875ad5b1a.png)

**Comment by SlyNet** [comment]
Unfortunately this kind of filters are not provided by survey solutions graphql api and as a result cannot be added to client library
