### ISSUE TITLE
Receiving server error 500 when assigning a workspace to a user

### ISSUE THREAD

**Issue by radyakin** [SlyNet/SurveySolutionsClient#2]
The following code fragment intended to assign workspace access to an existing user reportedly results in the server error 500:

```
public async Task can_assign()
{
    await susoClientAdminWS.AssignAsync(new AssignWorkspacesToUserRequest
    {
        UserIds = new Guid[] { Guid.Parse(aid) },
        Mode = AssignWorkspacesMode.Add,
        Workspaces = new[] { awsjm }
    });
}
```

See details here:
https://forum.mysurvey.solutions/t/assigning-a-workspace-to-an-existing-user/3790

**Comment by SlyNet** [comment]
If you try to assign a workspace for interviewer you need to specify supervisor id also. Unfortunately Survey Solutions does not return message about such error. Fix is in 2.0.1.0 version
