### ISSUE TITLE
Receiving error on request of Assignment details

### ISSUE THREAD

**Issue by Bacis55** [SlyNet/SurveySolutionsClient#3]
The following code results in the NotSupportedException error.
```
        public async Task can_get_assignment_details()
        {
            var response = await service.Assignments.DetailsAsync(2410);
            Assert.That(response, Is.Not.Null);
        }
```
```
System.NotSupportedException
  HResult=0x80131515
  Message=Deserialization of types without a parameterless constructor, a singular parameterized constructor, or a parameterized constructor annotated with 'JsonConstructorAttribute' is not supported. Type 'SurveySolutionsClient.Models.AbstractAnswer'. Path: $.Answers[0].Answer | LineNumber: 0 | BytePositionInLine: 98.
  Source=System.Text.Json
Inner Exception 1:
NotSupportedException: Deserialization of types without a parameterless constructor, a singular parameterized constructor, or a parameterized constructor annotated with 'JsonConstructorAttribute' is not supported. Type 'SurveySolutionsClient.Models.AbstractAnswer'.

```

**Comment by Bacis55** [comment]
Still is a problem to get assignments details or interviews details.
`client.Assignments.DetailsAsync(3000)`
`client.Interviews.DetailsAsync(Guid.Parse(id_dot))`

I got same error message on both:
Server responded with NotFound (404) status code. Check ResponseBody property for details

I`m using newest server version 21.06.02

**Comment by SlyNet** [comment]
Did you use https://www.nuget.org/packages/SurveySolutionsClient/2.0.1 version of a package?

**Comment by Bacis55** [comment]
Yes. 2.0.1.

**Comment by SlyNet** [comment]
Are you sure that headquarters url is configured properly? I tested it with latest headquarters docker image, and can receive assignment details:
![image](https://user-images.githubusercontent.com/209227/127181693-22b35bed-c1c7-46a0-ba7b-60e8c3007fd3.png)

404 errors usually indicate wrong endpoints

**Comment by Bacis55** [comment]
Yes, you was right. I miissed workspace in connection, but still is not okay.
![image](https://user-images.githubusercontent.com/65445700/127287075-06945ce2-3c36-4503-967c-d2ad83f2027d.png)

**Comment by Bacis55** [comment]
I found a problem, there is something wrong with questionaire because when i tried to get details from different questionaire its working okay. If you want to simulate a problem i can give you access in designer to this questionaire.

**Comment by SlyNet** [comment]
Ok, from error message I think I know what the problem could be. Will try to fix it in next release

**Comment by SlyNet** [comment]
Version 2.1 should handle described case. But still some more work needs to be done to implement all question types see #6
