### ISSUE TITLE
Survey solutions API .Net

### ISSUE THREAD

**Issue by kankaales** [SlyNet/SurveySolutionsClient#7]
Hello,
In c# I created a program which reads a list of interviewers(users) and assigns workspaces to users.
When run for the first time from VS IDE, the program throws the following error:

System.Text.Json.JsonException: ''<' is an invalid start of a value. Path: $ | LineNumber: 0 | BytePositionInLine: 0.'

When run for the second (third etc.) time, my program runs smoothly without errors.
When I close VS and reopen it, the error sometimes appears, sometimes not.
What should I do?
Thank you a lot.

**Comment by Bacis55** [comment]
Hi,
Every time I want to create unlimited assignment, I got error message. But unlimited assignment is created on server so just response of server looks bad. Looks like negative number of unlimited assignment (-1) is a problem.
Thank you
```
The JSON value could not be converted to System.Int32. Path: $.Assignment.Quantity | LineNumber: 0 | BytePositionInLine: 1289.
```
![image](https://user-images.githubusercontent.com/65445700/135633530-0392c369-aa65-469c-88ef-e36cf132eb64.png)

**Comment by kankaales** [comment]
Hello,
I am sorry, I do not understand. Is there anything I can do about the problem?
I have no access to the server.
Sorry to bother you but your assistance would be highly appreciated.
Thank you.

______________________________________________________________

**Comment by SlyNet** [comment]
Can you please provide a sample code you are trying to run?

**Comment by kankaales** [comment]
The same error sometimes occurs when we are trying to synchronize the collected data in the Intervewer app.
The second time I synchronize, everything is OK.
Can that be a problem on a server?

The code you are asking for is somewhat complicated.
I am giving only a fraction of it with relevant methods:

                susoClientAdmin = new SurveySolutionsApi(new HttpClient(), GetConfigurationAdmin());
                susoClientAdminWS = new SurveySolutionsApi(new HttpClient(), GetConfigurationAdmin()).WorkSpaces;


                Int16 iii = 0;
                Task<GraphQlResponse> t = should_be_able_to_get_list_of_interviewers(0);
                GraphQlResponse resp = await t;

                while (resp.Data.Users.Nodes.Count > 0)
                {
                    foreach (User u in resp.Data.Users.Nodes.ToList())
                    {
                        if (u.Workspaces.Contains(wsjm[i]))
                        {
                            DataRow dr = dtSurSol.NewRow();
                            dr["Email"] = u.Email;
                            dr["FullName"] = u.FullName;
                            dr["Id"] = u.Id;
                            dr["PhoneNumber"] = u.PhoneNumber;
                            dr["UserName"] = u.UserName;
                            dr["IsArchived"] = u.IsArchived;
                            dr["IsLocked"] = u.IsLocked;
                            dtSurSol.Rows.Add(dr);
                        }
                    }
                    iii += 1;
                    t = should_be_able_to_get_list_of_interviewers(iii);
                    resp = await t;
                }

                susoClient = null;
                susoClient = new SurveySolutionsApi(new HttpClient(), GetConfiguration(wsjm[i]));

                string ujm;
                Int16 kod;
                foreach (DataRow r in dtOraSouc.Rows)           //ty, které mají v Oraclu úlohu aktuálně přiřazenou
                {
                    ujm = r["UserName"].ToString();
                    aid = "";
                    kod = NajdiUziv(ujm);       // hledá v dtSurSol a dtSurSolVse uživatele s jménem ujm
                    if (kod==2)
                    {
                        try
                        {
                            RegisterUserModel rum = new RegisterUserModel();
                            rum.UserName = r["UserName"].ToString();
                            rum.Role = SurveySolutionsClient.Models.Roles.Interviewer;
                            rum.Password = "psw";
                            rum.Supervisor = "garant_ak";
                            rum.FullName = r["FullName"].ToString();
                            rum.Email = r["Email"].ToString();
                            rum.PhoneNumber = r["Telefon"].ToString();
                            Task tt = susoClient.Users.RegisterAsync(rum);
                            await tt;
                        }
                        catch
                        {
                            Console.WriteLine("failed");
                        }
                    }
                    if (kod == 1)
                    {
                        awsinfo = new AssignWorkspaceInfo(awsjm, Guid.Parse(asvid.ToString()));
                        Task tt = can_assign();
                        awsinfo = null;
                    }
                }

        public static SurveySolutionsApiConfiguration GetConfiguration(string jmWorkSpace)
        {
            Credentials susoCred = new Credentials("edomset", "psw");
            String susoURL = "http://sursol-pp-as01.ab.czso.cz/";
            SurveySolutionsApiConfiguration susoCFG = new SurveySolutionsApiConfiguration(susoCred, susoURL, jmWorkSpace);
            return susoCFG;
        }

        public short NajdiUziv(string pjm)
        {
            bool jejm = false;
            bool jejmws = false;
            foreach (DataRow dr in dtSurSol.Rows)
            {
                if (dr["UserName"].ToString() == pjm)
                {
                    jejmws = true;
                    break;
                }
                else
                {
                    foreach (DataRow dr2 in dtSurSolVse.Rows)
                    {
                        if (dr2["UserName"].ToString() == pjm)
                        {
                            aid = dr2["Id"].ToString();
                            jejm = true;
                            break;
                        }
                    }
                }
            }
            if (jejmws)
            {
                return 0;   //nic nevkládat
            }
            if (jejm)
            {
                return 1;   //nový workspace
            }
            return 2;       //nový tazatel i ws
        }

        public async Task<GraphQlResponse> should_be_able_to_get_list_of_interviewers(short i)
        {
            var builder = new HeadquartersQueryQueryBuilder()
                .WithUsers(new UsersQueryBuilder()
                        .WithNodes(new UserQueryBuilder().WithAllFields())            //bylo .WithAllScalarFields()
                        .WithFilteredCount()
                        .WithTotalCount(),
                    skip : i*100,
                    where: new UsersFilterInput
                    {
                        //Role = new RoleFilterInput { Eq = UserRoles.Interviewer }
                        Role = new RoleFilterInput { Eq = SurveySolutionsClient.GraphQl.UserRoles.Interviewer }
                    },
                    order: new[]
                    {
                        new UsersSortInput
                        {
                            FullName = SortEnumType.Asc
                        }
                    }) ;

            var result = await susoClientAdmin.GraphQl.ExecuteAsync<GraphQlResponse>(builder);

            Assert.That(result.Data.Users, Is.Not.Null);
            Assert.That(result.Data.Users.Nodes, Is.Not.Null.Or.Empty);
            Assert.That(result.Data.Users.Nodes.All(x => x.Role == SurveySolutionsClient.GraphQl.UserRoles.Interviewer));

            return result;
        }

        public async Task can_assign()
        {
            await susoClientAdminWS.AssignAsync(new AssignWorkspacesToUserRequest
            {
                UserIds = new Guid[] { Guid.Parse(aid) },
                Mode = AssignWorkspacesMode.Add,
                Workspaces = new AssignWorkspaceInfo[] { awsinfo }
            });
        }

**Comment by SlyNet** [comment]
If error is in interviewer app then it should not be related to your api usage. On first look I can't find any issue in it. What error message to get on interviewer app?

**Comment by kankaales** [comment]
I should not have written that it was the same error. Probably, it was not (the error message was different). It might have been a related problem, though. What the exact wording of the error message was, I do not know. Now, I am not getting the error, the synchronization runs smoothly.

**Comment by SlyNet** [comment]
If data appears within Headquarters application then bug is not related to api client. Please feel free to reopen ticket if you find a bug that is related to api calls.
