### ISSUE TITLE
Creating unlimited assignment error

### ISSUE THREAD

**Issue by Bacis55** [SlyNet/SurveySolutionsClient#8]
Hi,
Every time I want to create unlimited assignment, I got error message. But unlimited assignment is created on server so just response of server looks bad. Looks like negative number of unlimited assignment (-1) is a problem.
Thank you
```
The JSON value could not be converted to System.Int32. Path: $.Assignment.Quantity | LineNumber: 0 | BytePositionInLine: 1289.
```
![image](https://user-images.githubusercontent.com/65445700/135634749-709b0d40-b0b3-4087-a949-64af6a46fcaf.png)

**Comment by SlyNet** [comment]
Fixed in 3.1 version. [Sample](https://github.com/SlyNet/SurveySolutionsClient/blob/main/src/SurveySolutionsClient.Tests/AssignmentsTests.cs#L200) how to create an unlimited assignment
